export const ErrorCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  DEVICE_NOT_FOUND: 'DEVICE_NOT_FOUND',
  DEVICE_ALREADY_PROVISIONED: 'DEVICE_ALREADY_PROVISIONED',
  INVALID_SERIAL_FORMAT: 'INVALID_SERIAL_FORMAT',
  UNKNOWN_DEVICE_TYPE: 'UNKNOWN_DEVICE_TYPE',
  ZONE_NOT_FOUND: 'ZONE_NOT_FOUND',
  LOCATION_NOT_FOUND: 'LOCATION_NOT_FOUND',
  ALREADY_ACKNOWLEDGED: 'ALREADY_ACKNOWLEDGED',
  ALERT_RULE_NOT_FOUND: 'ALERT_RULE_NOT_FOUND',
  ALERT_EVENT_NOT_FOUND: 'ALERT_EVENT_NOT_FOUND',
  HAS_ATTACHED_DEVICES: 'HAS_ATTACHED_DEVICES',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  WEBHOOK_NOT_FOUND: 'WEBHOOK_NOT_FOUND',
  WEBHOOK_URL_FORBIDDEN: 'WEBHOOK_URL_FORBIDDEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  FORBIDDEN: 'FORBIDDEN',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
} as const;

export type ErrorCode = typeof ErrorCode[keyof typeof ErrorCode];
