listener 1883
protocol mqtt

allow_anonymous false
password_file /mosquitto/config/runtime/passwd
acl_file /mosquitto/config/runtime/acl

persistence true
persistence_location /mosquitto/config/runtime/data/

log_dest stdout
log_type warning
log_type error
