listener 1883
protocol mqtt

allow_anonymous false
password_file /data/passwd
acl_file /data/acl

persistence true
persistence_location /data/persistence/

log_dest stdout
log_type warning
log_type error
